### ISSUE TITLE
dell 7501 OC EFI

### ISSUE THREAD

**Issue by 87357163** [ShiinaKaze/vmess-kaze#1]
ShiinaKaze Can I have your OC EFI？ Dell 7501 also wants to install Mac OS，thank you。
E-mail：87357163@qq.com

**Comment by ShiinaKaze** [comment]
> ShiinaKaze Can I have your OC EFI？ Dell 7501 also wants to install Mac OS，thank you。
> E-mail：[87357163@qq.com](mailto:87357163@qq.com)

额。。。我一看你QQ邮箱，那就用中文吧，已经配好了，但是有些硬件还不能正常驱动，现阶段可以装机，然后背光板无法马上驱动——也就是需要开机后等2-5分钟后才会亮屏。

**Comment by 87357163** [comment]
哈哈，太好了，我不知道咋配置这个，能否帮忙传一份配置好的EFI啊
&nbsp;

您的朋友赵博敬上！


&nbsp;

**Comment by ShiinaKaze** [comment]
> 哈哈，太好了，我不知道咋配置这个，能否帮忙传一份配置好的EFI啊 &nbsp; 您的朋友赵博敬上！ &nbsp;

QQ联系，1515097306，请备注。
